apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: qdrant-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qdrant
  namespace: ecomm
  labels: 
    app: qdrant
spec:
  replicas: 1
  serviceName: qdrant
  selector:
    matchLabels:
      app: qdrant  
  template:
    metadata:
      labels:
        app: qdrant
    spec:
      containers:
      - name: qdrant
        image: qdrant/qdrant:v1.19.1
        ports:
        - containerPort: 6333
          name: http
        - containerPort: 6334
          name: grpc
        env:
        - name: QDRANT__STORAGE__PERFORMANCE__MAX__SEARCH__THREADS
          value: "0"
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests: 
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - name: qdrant-storage
          mountPath: /qdrant/storage
  volumeClaimTemplates:
    - metadata:
        name: qdrant-storage
      spec:
        accessModes: ["readWriteOnce"]
        storageClassName: "qdrant-gp3"
        resources:
          requests:
            storage: 50Gi

---

apiVersion: v1
kind: Service
metadata:
  name: qdrant-svc
  namespace: ecomm
  labels:
    apps: qdrant
spec:
  type: ClusterIP
  ports:
  - port: 6333
    targetPort: http
    name: http
  - port: 6334
    targetPort: grpc
    name: grpc
  selector:
    app: qdrant

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qdrant-ingress
  namespace: ecomm
  annotations:
    alb.ingress.kubernetes.io/group.name: ecomm-ingress-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /qdrant
            pathType: Prefix
            backend:
              service:
                name: qdrant-svc
                port:
                  number: 6333











        
