apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spark-workloads
spec:
  template:
    metadata:
      labels:
        workload-type: spark
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: spark-Ec2NodeClass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m6i","m6a","m7i","m7a","r6i","r6a","r7i","r7a"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
      taints:
        - key: spark-workload
          value: "true"
          effect: NO_SCHEDULE
  limits:
    cpu: "500"
    memory: "2000Gi"