apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-image-pull
  namespace: ecomm
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: ghcr-image-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}

  data:
    - secretKey: username
      remoteRef:
        key: github-secret-token
        property: username

    - secretKey: password
      remoteRef:
        key: github-secret-token
        property: password