apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: embeddings-nodepool
spec:
  template:
    metadata:
      labels:
        workload-type: embeddings

    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: embeddings-nodeclass

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: kubernetes.io/os
          operator: In
          values: ["linux"]

        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m", "c", "r"]

  limits:
    cpu: "500"

  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m