apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: tools
  labels:
    apps: mongo-express
spec:
  clusterIP: None 
  ports:
  - port: 8083
    targetPort: http
    name: mongo-express-http
  selector:
    app: mongo-express

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-express
  namespace: tools
  labels: 
    app: mongo-express
spec:
  replicas: 1
  serviceName: mongo-express
  selector:
    matchLabels:
      app: mongo-express 
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      serviceAccountName: mongo-express-sa
      initContainers:
      - name: download-documentdb-ca
        image: public.ecr.aws/aws-cli/aws-cli:2
        command:
          - /bin/sh
          - -c
          - |
            aws s3 cp s3://{cert_bucket}/certs/ca-bundle.pem
            chmod 0444 /certs/ca-bundle.pem
        volumeMounts:
          - name: documentdb-ca
            mountPath: /certs
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8083
          name: mongo-express-http
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "{mongo_uri}"

        - name: ME_CONFIG_MONGODB_SSL
          value: "true"

        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin" 

        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "password123"

        - name: ME_CONFIG_MONGODB_AUTH_DATABASE
          value: "admin"

        - name: ME_CONFIG_MONGODB_AUTH_SOURCE
          value: "admin"

        - name: ME_CONFIG_MONGODB_CA_FILE
          value: "/certs/ca-bundle.pem"

        - name: ME_CONFIG_HEALTH_CHECK_PATH
          value: "/status"
        
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests: 
            cpu: "1"
            memory: 4Gi
        volumeMounts:
        - name: documentdb-ca
          mountPath: /certs
          readOnly: true
        - name: mongo-express-storage
          mountPath: /mongo-express/data
volumeClaimTemplates:
- metadata:
    name: mongo-express-storage
  spec:
    accessModes: ["readWriteOnce"]
    storageClassName: "tools-gp3"
    resources:
      requests:
        storage: 50Gi











        
