apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: tools-gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-insight
  namespace: ecomm-tools
  labels:
    app: redis-insight
spec:
  replicas: 1

  serviceName: redis-insight-svc

  selector:
    matchLabels:
      app: redis-insight

  template:
    metadata:
      labels:
        app: redis-insight

    spec:
      containers:
        - name: redis-insight
          image: redis/redisinsight:latest
          imagePullPolicy: Always

          ports:
            - name: redis-insight-http
              containerPort: 5540
              protocol: TCP

          env:
            - name: RI_REDIS_HOST
              value: "{redis_host}"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /status
              port: redis-insight-http
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /status
              port: redis-insight-http
            initialDelaySeconds: 30
            periodSeconds: 30

          volumeMounts:
            - name: redis-insight-storage
              mountPath: /redis/insight
  volumeClaimTemplates:
    - metadata:
        name: redis-insight-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: tools-gp3
        resources:
          requests:
            storage: 50Gi

---

apiVersion: v1
kind: Service
metadata:
  name: redis-insight-svc
  namespace: ecomm-tools
  labels:
    app: redis-insight
spec:
  type: ClusterIP
  selector:
    app: redis-insight
  ports:
    - name: redis-insight-http
      port: 5540
      targetPort: redis-insight-http
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  namespace: ecomm-tools
  annotations:
    alb.ingress.kubernetes.io/group.name: ecomm-ingress-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /redis-insight
            pathType: Prefix
            backend:
              service:
                name: redis-insight-svc
                port:
                  number: 5540